# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ramix}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Thierry Zires}]
  s.date = %q{2012-02-08}
  s.description = %q{Ramix is a command-line tool for initializing a new rails application.Just the same as rails but adding more additional options.}
  s.email = %q{zshuaibin@gmail.com}
  s.executables = [%q{ramix}]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "bin/ramix",
    "lib/ramix.rb",
    "lib/ramix/app_generator.rb",
    "lib/ramix/builder.rb",
    "lib/ramix/commands.rb",
    "lib/ramix/helpers.rb",
    "lib/ramix/template.rb",
    "lib/ramix/version.rb",
    "ramix.gemspec",
    "recipes/authentication.rb",
    "recipes/china.rb",
    "recipes/front_end.rb",
    "recipes/home.rb",
    "recipes/nosql.rb",
    "recipes/omniauth.rb",
    "recipes/template_language.rb",
    "test/fixtures/diff_recipe.rb",
    "test/fixtures/recipe.rb",
    "test/helper.rb",
    "test/test_builder.rb",
    "test/test_template.rb"
  ]
  s.homepage = %q{http://github.com/zires/ramix}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{new rails application generator}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, ["~> 0.14.6"])
      s.add_runtime_dependency(%q<hpricot>, [">= 0"])
    else
      s.add_dependency(%q<thor>, ["~> 0.14.6"])
      s.add_dependency(%q<hpricot>, [">= 0"])
    end
  else
    s.add_dependency(%q<thor>, ["~> 0.14.6"])
    s.add_dependency(%q<hpricot>, [">= 0"])
  end
end

